### ISSUE TITLE
Need minimum hardware recommendations

### ISSUE THREAD

**Issue by paimpozhil** [mistio/mist.io#210]
Hi 

I ran this in a 1G droplet at Digitalocean and got many out of memory issues.

Adding Swap didnt help. the SSH sessions started timing out .

So I am trying now with 2G Droplet.. however it is useful to know what kind of specs we need for xx servers/etc.

Also you dont have to update anything.. just send your recommendations here and I would happily contribute changes to your repo with pull requests :)

**Comment by mgogoulos** [comment]
hardware requirements specified on the new version of mist.io (2.0.0) - https://github.com/mistio/mist.io
