### ISSUE TITLE
Docker parameters

### ISSUE THREAD

**Issue by tomfuie** [mistio/mist.io#312]
Successfully creating/stopping/starting a docker process -- thank you.

Currently, the docker run is "/bin/sh -c 'cd / && ./init.sh'".  How might other parameters be part of the actually run command?
Basic mysql example: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=mysecretpassword -d mysql

I see the post run script afterwards..doesn't help for the startup of a specific container.

What did I miss?

Best,
Tom

**Comment by commixon** [comment]
@tomfuie If you'd like to take a look at the docker machine creation, we now support running docker containers and passing the command to run, together with ENV variables.
