### ISSUE TITLE
Prerender all buttons

### ISSUE THREAD

**Issue by gtsop** [mistio/mist.io#367]
Jquery mobile parses the DOM to find all the elements with the attribue data-role in order to render them. Buttons are very easy to pre-render by writting all the appropriate classes jqm appends. For instance this element:

```
<a data-role="button" data-theme="b" data-mini="true" data-icon="gear"></a>
```

can be converted into this one:

```
<a class="ui-btn ui-btn-b ui-mini ui-btn-icon-right ui-icon-gear"></a>
```

which will decrease the time spent on rendering widgets and eventually the client's CPU load

**Comment by dimitrisMaf28** [comment]
https://github.com/mistio/mist.io/pull/446

**Comment by dimitrisMaf28** [comment]
https://github.com/mistio/mist.io/pull/456
