### ISSUE TITLE
Add support for Vultr?

### ISSUE THREAD

**Issue by KeiroD** [mistio/mist.io#462]
Would it be possible to add support for Vultr? Their API stuff is here: https://www.vultr.com/api/

Adding support for them would be great.

**Comment by cpsaltis** [comment]
@KeiroD thanks for the feedback.

Unfortunately Vultr support is not in our short-term roadmap. Having said that, libcloud supports Vultr so it wouldn't be very complicated for someone to add it. If you're interested to contribute this we'd be happy to assist, review and merge your code to master. 

We're about to publish a post on how you can add support for new provider to mist.io, so stay tuned and you'll get a better idea on how much work this could be.

**Comment by KeiroD** [comment]
@cpsaltis Awesome.

Glad to hear it. I'm really liking the clean interface you guys have going on here and adding support for more providers is always a good thing.

We'd definitely be interested in getting support for Vultr added. We'll make a fork of your repository and work on adding such support and contribute back to master. :)

I'll keep an eye out for that post as that'll definitely help as you guys don't seem to have documentation at all, especially if one is intending on using the open-source version.

Sidenote: Will that post also include instructions for how to tie it into your own billing system?

**Comment by cpsaltis** [comment]
@KeiroD here is the post as promised http://blog.mist.io/post/117233356986/adding-a-new-provider-in-mist-io-the-host-virtual

There is no need to tie anything into the billing system, unless I don't understand your question. Regarding documentation check out here https://mist.io/docs/index.html. Let me know what you think.

If you plan to work on Vultr I can arrange for someone on our team to help you directly. Just send me your contact details at chris at mist.io

**Comment by KeiroD** [comment]
@cpsaltis Well... if one wishes to use mist.io for their control panel in place of say... SolusVM, they could do that with mist.io.

In fact, that's what I plan on doing, myself. However... I'll be checking out the documentation to see if it's possible to tie into our billing system in order to bill customers for usage of VPSes.

Hence, the question. As for planning on working on Vultr... yes, I am. I will be testing this out in May. At the moment, I don't have a reliable method of testing things, so I'm reserving testing and development of a Vultr plugin for May and thereon.

**Comment by cpsaltis** [comment]
@KeiroD got it, you're trying to offer this to your end customers as a small time IaaS provider. It's definitely possible but it will need work and tweaking. Mist.io wasn't meant to be a SolusVM replacement.

How about we arrange a brief meeting over the next few days to discuss and see if there is a way we could help you? Email me at chris at mist.io and let's pick it up form there.

**Comment by KeiroD** [comment]
Closing this as I created the port needed and all PRs have been approved.

Thanks for helping me to help you guys add Vultr support!
