### ISSUE TITLE
slow performance

### ISSUE THREAD

**Issue by steve-netskope** [mistio/mist.io#491]
I have registered 20 KVM hosts (libvirt) that has over 270 guest machines. It takes over 30 seconds to display machines when 'Machines' button has been clicked. Is this normal? I have plenty of resouce (memory and CPU) available from the machine.

**Comment by Clopy** [comment]
Hi Steve,

You're right, the UI does slow down considerably once you get over 150 machines. There is already work underway to reduce the browser load though. Also, keep in mind that so far Chrome plays better with Mist.io compared to Firefox in terms of speed.

**Comment by mgogoulos** [comment]
pagination has been added to the machines list which results in significant performance improvements
