### ISSUE TITLE
buildout fails - ubuntu 14.04.3 - amqp version conflict

### ISSUE THREAD

**Issue by V3XATI0N** [mistio/mist.io#558]
Buildout proceeds normall untils MarkupSafe, which fails with the following error:

```
We have the best distribution that satisfies 'MarkupSafe>=0.9.2'.
Picked: MarkupSafe = 0.23
While:
  Installing mist.
Error: There is a version conflict.
We already have: amqp 1.4.6
but kombu 3.0.27 requires 'amqp<2.0,>=1.4.7'.
```
If I manually change the requirement in kombu's requires.txt to allow 1.4.6, the buildout continues and completes successfully, but of course the result is a non-functional installation since the rabbitmq component will not run.

**Comment by mgogoulos** [comment]
Hi,
edit buildout.cfg and append these two lines:
```
Pillow = 2.9.0
kombu = 3.0.26 
```
then re-run buildout (./bin/buildout -v) 

Then run supervisord
```
user@user:~/mist.io$ ./bin/supervisord 
```
And check services are running. 
```
user@user:~/mist.io$ ./bin/supervisorctl status
```
Some times rabbitmq won't start, in this case check that epmd is started
```
user@user:~/mist.io$ ps aux|grep epmd
```
If it is not started, start it with 
```
user@user:~/mist.io$ epmd -daemon
```
and restart services
```
user@user:~/mist.io$ ./bin/supervisorctl restart all
```

Hope this helps!

**Comment by V3XATI0N** [comment]
That worked! Thanks
