### ISSUE TITLE
Default login user

### ISSUE THREAD

**Issue by gshiva** [mistio/mist.io#562]
I installed https://github.com/rolikeusch/docker-mistio and added a bare metal server (which is a Vagrant machine)

If I click on the Machine, it is saying Monitoring Disabled. To enable it, it asks for a login.

What is the default login? If not present how do I add one?

**Comment by gshiva** [comment]
Actually noticed that build was done 2 years ago.

**Comment by mgogoulos** [comment]
Hi, 

lots of new features have been added since that build! There has been a major rewrite of the UI recently so I suggest you try the installation using buildout, on http://github.com/mistio/mist.io/

Cheers
