### ISSUE TITLE
cannot buildout

### ISSUE THREAD

**Issue by teoxrr** [mistio/mist.io#580]
get an error running buildout on ubuntu 14.04:

Running "requirejs:mistjs" (requirejs) task
{ [Error: Error: ENOENT, no such file or directory '/mist.io/src/mist/io/static/dist/jquery/jquery.js'
    at Error (native)
]
  originalError:
   { [Error: ENOENT, no such file or directory '/mist.io/src/mist/io/static/dist/jquery/jquery.js']
     errno: -2,
     code: 'ENOENT',
     path: '/mist.io/src/mist/io/static/dist/jquery/jquery.js',
     syscall: 'open',
     fileName: '/mist.io/src/mist/io/static/dist/jquery/jquery.js' } }
While:
  Installing grunt.

**Comment by teoxrr** [comment]
I was running as root, so some packages couldn't build

**Comment by mgogoulos** [comment]
Hi, the buildout has to be run as user and will fail if run as root!
