### ISSUE TITLE
buildout fails

### ISSUE THREAD

**Issue by honza801** [mistio/mist.io#596]
hi,

command 
./bin/buildout -v
fails with following

i'm using debian 8, python 2.7.9

jan

...
Installing grunt.
Running "emberTemplates:compile" (emberTemplates) task
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/application.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/backend_add.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/backend_button.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/backend_edit.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/dialog.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/file_upload.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/graph_button.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/graph_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/graph_list_bar.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/graph_list_control.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/graph_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/home.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/image.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/image_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/image_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/images.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/index.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/ip_address_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/key.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/key_add.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/key_edit.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/key_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/key_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/keys.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/log_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/log_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/login.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_add.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_edit.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_keys.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_keys_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_monitoring.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_power.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_run_script.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_shell.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_tags.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machine_tags_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/machines.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/messagebox.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/metric_add.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/metric_add_custom.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/metric_node.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/missing.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/network.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/network_create.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/network_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/network_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/networks.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/rule.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/rule_edit.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/rule_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script_add.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script_edit.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script_log_list.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/script_run.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/scripts.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/subnet_list_item.hbs. Used --force, continuing.
>> Error: ENOENT, no such file or directory './bower_components/ember/ember-template-compiler.js'
Warning: Ember Handlebars failed to compile src/mist/io/static/js/app/templates/user_menu.hbs. Used --force, continuing.

Running "symlink:dist" (symlink) task
Creating symlink to ../../../../dist/ at src/mist/io/static/dist...OK

Running "symlink:jquery" (symlink) task
Creating directory dist...OK
Creating symlink to ../bower_components/jquery/dist/ at dist/jquery...OK

Running "symlink:jqm" (symlink) task
Creating symlink to ../bower_components/jquery-mobile-bower/ at dist/jqm...OK

Running "symlink:ember" (symlink) task
Creating symlink to ../bower_components/ember/ at dist/ember...OK

Running "symlink:requirejs" (symlink) task
Creating symlink to ../bower_components/requirejs/ at dist/requirejs...OK

Running "symlink:requirejs_text" (symlink) task
Creating symlink to ../bower_components/requirejs-text/ at dist/requirejs-text...OK

Running "symlink:sockjs" (symlink) task
Creating symlink to ../bower_components/sockjs/ at dist/sockjs...OK

Running "symlink:md5" (symlink) task
Creating symlink to ../bower_components/md5/ at dist/md5...OK

Running "symlink:d3" (symlink) task
Creating symlink to ../bower_components/d3/ at dist/d3...OK

Running "symlink:c3" (symlink) task
Creating symlink to ../bower_components/c3/ at dist/c3...OK

Running "symlink:term" (symlink) task
Creating symlink to ../bower_components/term.js/ at dist/term.js...OK

Running "symlink:images" (symlink) task
Creating symlink to ../src/mist/io/static/images at dist/images...OK

Running "symlink:fonts" (symlink) task
Creating symlink to ../src/mist/io/static/fonts at dist/fonts...OK

Running "symlink:states" (symlink) task
Creating symlink to ../src/mist/io/static/states at dist/states...OK

Running "requirejs:mistjs" (requirejs) task
{ [Error: Error: ENOENT, no such file or directory '/opt/mist.io/src/mist/io/static/dist/jquery/jquery.js'
    at Error (native)
]
  originalError: 
   { [Error: ENOENT, no such file or directory '/opt/mist.io/src/mist/io/static/dist/jquery/jquery.js']
     errno: -2,
     code: 'ENOENT',
     path: '/opt/mist.io/src/mist/io/static/dist/jquery/jquery.js',
     syscall: 'open',
     fileName: '/opt/mist.io/src/mist/io/static/dist/jquery/jquery.js' } }
While:
  Installing grunt.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/mist.io/eggs/zc.buildout-2.4.7-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/opt/mist.io/eggs/zc.buildout-2.4.7-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/opt/mist.io/eggs/zc.buildout-2.4.7-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/opt/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 56, in install
    self.execute()
  File "/opt/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 69, in execute
    run_commands(cmds, self.shell)
  File "/opt/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 39, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/bin/bash /tmp/tmpiy1VPf/run' returned non-zero exit status 1

**Comment by mgogoulos** [comment]
Hi, the buildout has to be run as user and will fail if run as root! So please login as user, create a new directory, clone https://github.com/mistio/mist.io and re-run the buildout.

**Comment by honza801** [comment]
works now

sorry for disturbing (i've finally read all the docs, which says the same)

jan

**Comment by cpsaltis** [comment]
Happens to me all the time, I get too excited! Truth is we need to make installation simpler and we're working on it.

Just a out of curiosity, what problem are you looking to solve with Mist.io and how did you find out about it?

**Comment by honza801** [comment]
i need some cloud/virtual manager for hosts running libvirt.
i've found it on http://www.linux-kvm.org/page/Management_Tools

**Comment by cpsaltis** [comment]
Got it, thanks. Stay tuned for our next iteration on libvirt support in the next few weeks. The first thing we'll deliver will be provisioning.
