### ISSUE TITLE
libvirt driver fails on mac homebrew client

### ISSUE THREAD

**Issue by mjhilt** [mistio/mist.io#599]
The libvirt client assumes the libvirt socket corresponds to the client's installation. When using a homebrew based install of libvirt, this is some non-standard path. You can specify it in the connection uri, however.

The following patch would fix the issue assuming you always want to connect to a linux based host.

```
 libcloud/compute/drivers/libvirt_driver.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/libcloud/compute/drivers/libvirt_driver.py b/libcloud/compute/drivers/libvirt_driver.py
index 23c0a3b..32ddbca 100644
--- a/libcloud/compute/drivers/libvirt_driver.py
+++ b/libcloud/compute/drivers/libvirt_driver.py
@@ -92,7 +92,7 @@ class LibvirtNodeDriver(NodeDriver):
                 except:
                     raise Exception("Make sure host is accessible and ssh port %s is open" % ssh_port)

-                uri = 'qemu+ssh://%s@%s:%s/system?keyfile=%s&no_tty=1&no_verify=1' % (user, host, ssh_port, ssh_key)
+                uri = 'qemu+ssh://%s@%s:%s/system?keyfile=%s&no_tty=1&no_verify=1&socket=/var/run/libvirt/libvirt-sock' % (user, host, ssh_port, ssh_key)
             else:
                 #tcp connection
                 uri = 'qemu+tcp://%s:5000/system' % host
-- 
2.4.6
```

**Comment by mgogoulos** [comment]
Thanks a lot for this! I don't have a mac but I have heard from others that libvirt installation is not straightforward on mac. Will try to find a test environment to try this.

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
