### ISSUE TITLE
Does the open source version support free server monitoring?

### ISSUE THREAD

**Issue by meulie** [mistio/mist.io#627]
Hi all,

Just wondering whether this self-hosted, open source version gives me free server monitoring? Or is that _only_ supported by the paid version on https://mist.io/ ?

**Comment by mgogoulos** [comment]
Hi, 

monitoring is part of the Saas - https://mist.io.You can use the open source version for management of your clouds and enable monitoring through an account on the Saas. Thus you will be using mist.io monitoring servers, on your local installation of mist.io.

We are moving fast towards releasing the monitoring part as open source - packaged under docker containers for easy usage- but I cannot estimate when this will be done. 

Regards,
Markos

**Comment by cpsaltis** [comment]
What problem are you looking to solve with Mist.io @meulie? What's your setup like?
