### ISSUE TITLE
Server monitoring in the opensource version?

### ISSUE THREAD

**Issue by maxa4e** [mistio/mist.io#646]
The opensource version requires me to login to mist.io ( popup modal ) when clicking the "server monitor" button. Is it possible to have this feature without a mist.io account ?

It feels a bit like an advertisement for mist.io having this modal if this is the opensource version why is there mention to mist.io at all in such a way?

Very amazing project love to contribute hope this issue can be resolved. 
Since the documentation of opensource version also links to the mist.io documentation its not clear to me how to enable above without an account.

**Comment by dimrozakis** [comment]
Hi @maxa4e 

Monitoring is currently part of the mist.io SaaS, but we plan to move this functionality to the open source mist.io soon.

**Comment by mgogoulos** [comment]
Hi @maxa4e,

monitoring is part of the Saas - https://mist.io.You can use the open source version for management of your clouds and enable monitoring through an account on the Saas. Thus you will be using mist.io monitoring servers, on your local installation of mist.io.

As dimrozakis wrote we are moving fast towards releasing the monitoring part as open source - packaged under docker containers for easy usage- but I cannot estimate when this will be done.

You are very welcome to contribute to the project with suggestions, requests and code!

Cheers

**Comment by maxa4e** [comment]
Would be great, keep looking an eye on this project. 
Mist.io seems the only real goog all in one solution and monitoring the containers without having to use the online account would be awesome.

**Comment by k0r8i** [comment]
... are there any news regarding monitoring containers? :)

**Comment by mgogoulos** [comment]
Hi k0r8i, we are still in the middle of the migration of this functionality from the Saas -https://mist.io - to the open source mist.io

**Comment by splashx** [comment]
Hi guys. First of all great work :) Any update on the migration of the monitoring feature?

**Comment by ferhimedamine** [comment]
Same question here, when is monitoring gonna be included within open source version of mist.io
