### ISSUE TITLE
CoreOS local instance, no images found

### ISSUE THREAD

**Issue by maxa4e** [mistio/mist.io#647]
I have several images on my local CoreOS installation.

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
dockerui/dockerui          latest              9c51054cd79b        3 days ago          6.132 MB
registry                   latest              bdd0d98559dd        8 days ago          422.8 MB
mist/mistio                latest              6f880270d202        3 months ago        1.113 GB
atcol/docker-registry-ui   latest              2a29b9167376        8 months ago        890.5 MB
```

None of them are listed in the UI though.
Is there documentation on how to get the images to list? I have added ssh key and able to see the machine "CoreOs" running with basic uptime.

I have started the local registry also in case assuming mist.io would use this for searching all images;

```
docker run \
    -d \
    --name private_registry \
    -e SETTINGS_FLAVOR=local \
    -e STORAGE_PATH=/registry-storage \
    -e SEARCH_BACKEND=sqlalchemy \
    -e LOGLEVEL=DEBUG \
    -v /docker/registry/storage:/registry-storage \
    -u 10000 \
    -p 5000:5000 \
    registry
```

**Comment by mgogoulos** [comment]
Hi, 

The CoreOS support is very basic at the moment, it is just like adding it as a standalone server (Other server on the add cloud wizard) so this is why we don't advertise it much.
However we are planning to add functionality for CoreOS in the next 2 months, we will inform you through the blog and newsletter. 

You mention you didn't find any images, so I suppose you want to deploy docker containers, if this is the case you can expose the docker API and add it to mist.io as a Docker cloud - http://docs.mist.io/article/20-adding-docker

Thus you will be able to see the containers (running and stopped), list images, create and deploy containers

Hope this helps.

**Comment by maxa4e** [comment]
Looking forward to more features, i think it will help push mist.io forward in the opensource community and would work 2 ways.
