### ISSUE TITLE
Creating a machine with just a name is not working

### ISSUE THREAD

**Issue by dogobgyn** [mistio/mist.io#662]
I am using Docker to deploy mist.io.

**Steps to reproduce:**
Execute this 
```docker pull mist/mistio```
```docker run -d -p 8000:8000 mist/mistio```

Then go to:
dockeradress:8000 and add your docker cloud.

Then browse to images, and click an image.

Click create machine and enter a name.

You should be able to click the launch button. However it's still disabled.

To be able to launch with just the name you can enter something in the command field, then enter something in the name field(Then the launch button will become clickable). 

And lastly if you delete the command you've just typed the launch button will still be clickable.

**Comment by mgogoulos** [comment]
Hi @dogobgyn , this seems like a UI issue. Thanks for reporting, we will have a look and address the issue.

Best, 
Markos

**Comment by mgogoulos** [comment]
this is fixed now
