### ISSUE TITLE
Documentation does not have all necessary ubuntu packages

### ISSUE THREAD

**Issue by mzhaase** [mistio/mist.io#675]
On Ubuntu Server 15.04, you need these packages in addition to the ones mentioned, or rabbitMQ fails:

build-essential git libpcre3-dev python-lxml gcc libxml2

Also, might be worth mentioning how to change listen address.

**Comment by mgogoulos** [comment]
Hi, 

I'll try a buildout on Ubuntu 15.04 and update the docs with the packages you mention, thanks for reporting. Also we'll add a section with how to change the listen address, some people were surprised when it used to bind to 0.0.0.0 so we changed that to be the localhost interface, in any case it should be more straightforward from the docs how to change that. 

Cheers

**Comment by mgogoulos** [comment]
docs are updated now, closing
