### ISSUE TITLE
Version conflict while processing requirement Sphinx==1.3.4 (constrained to Sphinx==1.3.4)

### ISSUE THREAD

**Issue by Kawohl** [mistio/mist.io#679]
I tried to install mist.io and got this error:

`Version conflict while processing requirement Sphinx==1.3.4 (constrained to Sphinx==1.3.4)
While:
  Installing devtools.
Error: There is a version conflict.
We already have: Sphinx 1.3.5
`
Seems that the requirement brakes because the version number is to high. Does anybody know a workaround?

**Comment by mgogoulos** [comment]
Hi, seems like a dependency issue,  vi buildout.cfg and remove sphinx. Then rerun the buildout

```
./bin/buildout -vN
```

and you should be fine.

**Comment by Kawohl** [comment]
Wow that was quick!

**Comment by cpsaltis** [comment]
Hi @Kawohl thanks for reaching out.
Just out of curiosity, what would you like to achieve with Mist.io?
I'd love to hear your feedback.

**Comment by Kawohl** [comment]
@cpsaltis I just got a new machine and wanted a webui  to manage my kvm machines. 
mist.io was an interesting read and i just wanted to check it out..... ;-)

**Comment by mario-olivarez** [comment]
Hi Jonathan,

Just out of curiosity, is your new KVM machine for work or play?

Cheers,

Mario
ᐧ

Mario Olivarez

Mist.io
415-596-3088 | mario@mist.io
620 Folsom St. San Francisco, CA 94107

**Comment by Kawohl** [comment]
Just for Playing around.....
