### ISSUE TITLE
Running Mist.io on the KVM server -> ALLOW_LIBVIRT_LOCALHOST

### ISSUE THREAD

**Issue by romu70** [mistio/mist.io#692]
Hi,
I'm trying to give Mist.io a shot to check if it can fulfil our need which is pretty simple: offer a good web interface to drive our VMs, those VMs are standing on a single VMs server.

Both KVM and Mist.io run on the same server, and when I try to plug Mist.io on KVM, I get:  ALLOW_LIBVIRT_LOCALHOST error code.

Any solution? Thanks.

**Comment by mgogoulos** [comment]
Sure, edit file src/mist/io/config.py and set ALLOW_LIBVIRT_LOCALHOST to True. That will be:

```
ALLOW_LIBVIRT_LOCALHOST = settings.get('ALLOW_LIBVIRT_LOCALHOST', True)
```
then you'll have to restart mist.io for the setting to take effect

```
user@user:~/mist.io$ ./bin/supervisorctl stop all; ./bin/supervisorctl shutdown ; sleep 10; ./bin/supervisord 
```

and make sure all services are running with
```
user@user:~/mist.io$ ./bin/supervisorctl status
```

Hope mist.io fulfills your needs!

**Comment by mgogoulos** [comment]
Hi, 

did you try the above? 

Cheers

**Comment by romu70** [comment]
Hi @mgogoulos, sorry I was busy on few more urgent tasks.

Yes it works, thanks a lot for the trick, perfect!

**Comment by jryburn** [comment]
I have a very similar requirement but I have mist.io running inside a docker container. How can I edit the src/mist/io/config.py file? I tried opening a bash shell inside the container and I can cat the file and see that it is set to False. However, I cannot find a program inside the container to edit files (vi, emacs, nano, etc.).
