### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by r3pek** [mistio/mist.io#705]
Hi!

I wanted to package the opensource version of mist.io, but as a packager, I can't really get a version out of the tree without using git directly. This poses 2 problems for the users/packagers:
- Users think that being a -git package, it's a developing package, meaning, it's unstable and subject to breakage
- Packagers don't know when to version bump the package for a new release since it's only based on commits.

Tagging on github really helps solving those 2 issues since github generates source packages based on the tagged commit.

**Comment by mgogoulos** [comment]
Hi r3pek, 

you are very right, in fact we have been using tagging but at some point have stopped. We should continue that now. Are you contributing to some Linux distribution? If so which one? 

Cheers

**Comment by r3pek** [comment]
Hi @mgogoulos 

I will package mist for Arch Linux as soon as I have a recent tag. Doesn't make much sense to release something that is 2 years old :-/

**Comment by mgogoulos** [comment]
Hi r3pek, 

I've just tagged https://github.com/mistio/mist.io/releases/tag/0.9.9 so that you can use. Would love to see it packaged with Arch Linux! 

Keep us updated and feel free to ask if you have issues. 

Cheers,
Markos

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io

Let us know if you package it on Arch Linux or some other Linux distribution.

Cheers
