### ISSUE TITLE
Failed to set the size for disk

### ISSUE THREAD

**Issue by gen1321** [mistio/mist.io#707]
when trying to create machine i got this error. any fixes??

2016-03-04 17:45:30,796 INFO uWSGIWorker4Core0 views - exception_handler_mist: MistError: MachineCreationError("Machine creation failed: KVM, got exception Failed to set the size for disk /var/lib/libvirt/images/sadfhjkl.img: WARNING: Image format was not specified for '/var/lib/libvirt/images/sadfhjkl.img' and probing guessed raw.\n         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.\n         Specify the 'raw' format explicitly to remove the restrictions.\n",)
[pid: 2524|app: 0|req: 5/58] 127.0.0.1 () {48 vars in 850 bytes} [Fri Mar  4 17:45:28 2016] POST /clouds/4miuMQuyt4Bcf7z8hPTjrvFQfqCo/machines => generated 416 bytes in 2740 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)

**Comment by mgogoulos** [comment]
Hi, 

at that point it does run these two commands:

```
sudo qemu-img convert image_path /var/lib/libvirt/images/sadfhjkl.img
```
which succeeds, and then 
```
sudo qemu-img resize /var/lib/libvirt/images/sadfhjkl.img disk_size
```
the second command fails. Can you try the last command and paste the output? Eg

```
sudo qemu-img resize /var/lib/libvirt/images/sadfhjkl.img 5G
```

What is the OS on that server?

Cheers

**Comment by gen1321** [comment]
gen1321@hawkeye:~$ sudo qemu-img resize /var/lib/libvirt/images/sadfhjkl.img 5G
WARNING: Image format was not specified for '/var/lib/libvirt/images/sadfhjkl.img' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
Image resized.

**Comment by mgogoulos** [comment]
Thanks for the output, really helpful! This is just a warning, so the parsing shouldn't consider the command as failed, since the disk image is finally resized at the size specified by the user. I will make sure this is added. 

What do you think so far about the overall experience with KVM management? 

Cheers

**Comment by gen1321** [comment]
Sry can't give you a feed back cuz it do not work for me. I decide to use mist + docker insted

**Comment by mgogoulos** [comment]
this has been fixed, closing

**Comment by cpsaltis** [comment]
Just out of curiosity, what problem are you looking to solve with Mist.io @gen1321?
