### ISSUE TITLE
Use mist.io with existing rabbitmq

### ISSUE THREAD

**Issue by grepwood** [mistio/mist.io#715]
Hi everyone,

I'd like to use mist.io with an existing instance of rabbitmq rather than a new one that the virtualenv makes. It's already serving some other services like sensu.

Any help with that would be greatly appreciated. I don't think I did see a config parameter saying where mist.io should look for rabbitmq.

**Comment by mgogoulos** [comment]
Hi grepwood, 

on you mist.io installation, file parts/supervisor/supervisord.conf has the commands that are run by supervisord.
You can see there that process rabbitmq is started from file parts/rabbitmq/sbin/rabbitmq-server so have a look what is there, I suppose you can make it working with an existing rabbitmq server running, though I haven't tried that. 

If you make changes to parts/rabbitmq/sbin/rabbitmq-server, they can take effect by restarting rabbitmq with supervisorctl 

```
user@user:~/mist.io$ ./bin/supervisorctl restart rabbitmq
```

However if you make changes to parts/supervisor/supervisord.conf you have to restart supervisord itself. 

```
user@user:~/mist.io$ ./bin/supervisorctl shutdown ; sleep 10; ./bin/supervisord

```

If you try that let us know!

**Comment by grepwood** [comment]
Hi,
I've decided not to do a multi-node single-host cluster and commented out rabbit completely out of the parts/supervisor/supervisord.conf file.
What I get now is failed login attempts to the currently running rabbitmq server, and this is popping up in its logs:
```
=ERROR REPORT==== 15-Mar-2016::15:21:38 ===
Channel error on connection <0.15502.0> (127.0.0.1:47595 -> 127.0.0.1:5672, vhost: '/', user: 'guest'), channel 1:
operation basic.publish caused a channel exception not_found: "no exchange 'mist_debug' in vhost '/'"
```

**Comment by mgogoulos** [comment]
Hi, 

have a look on src/mist/io/config.py These two lines interest you:

```
AMQP_URI = settings.get("AMQP_URI", "localhost:5672")
BROKER_URL = settings.get("BROKER_URL", "amqp://guest:guest@127.0.0.1/")
```

Because of the way rabbitmq is tight to mist.io I think it will require a significant work to get it working on your existing rabbitmq server, because vhosts, and credentials are not in place, it expects to connect to rabbitmq on 5672 port as a single vhost and many components use it on this way. If you can't 'assign' this port to mist.io, I think it will just be easier to start mist.io rabbitmq on another port (through settings on parts/rabbitmq/sbin/rabbitmq-server) and make mist.io aware of it through the above settings, on src/mist/io/config.py

Hope this helps!

**Comment by grepwood** [comment]
That helps a bit. I changed the user and password, but now I can't get access to the vhost.
```
BROKER_URL = settings.get("BROKER_URL", "amqp://mistio:testpassword@127.0.0.1/mist")
```
```
=ERROR REPORT==== 16-Mar-2016::09:00:31 ===
Error on AMQP connection <0.12810.1> (127.0.0.1:60008 -> 127.0.0.1:5672, user: 'mistio', state: opening):
access to vhost 'mist' refused for user 'mistio'
```
After I changed the URL to `amqp://mistio:testpassword@127.0.0.1//mist`, the message I get regards the vhost `''`.

**Comment by grepwood** [comment]
Doing this caused a different issue to crop up - the loading bar of mist.io, when visiting any mist.io page, would not run full course and get stuck in about 90%.

**Comment by grepwood** [comment]
Which of the parts is causing this?
```
=ERROR REPORT==== 16-Mar-2016::10:17:26 ===
Channel error on connection <0.17494.1> (127.0.0.1:36073 -> 127.0.0.1:5672, vhost: '/', user: 'guest'), channel 1:
operation exchange.declare caused a channel exception not_found: "no exchange 'mist-user_noone' in vhost '/'"
```

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
