### ISSUE TITLE
KVM on Localhost

### ISSUE THREAD

**Issue by dalenoe** [mistio/mist.io#738]
I am having a problems with kvm on localhost. Where does said variable go "ALLOW_LIBVIRT_LOCALHOST" ? The control panel says to add that, but doesn't say where. First time installing the open source mist.io

**Comment by mgogoulos** [comment]
Hi, on mist.io root folder, edit file settings.py 

```
user@user:~/mist.io$ vi settings.py
```

add line

ALLOW_LIBVIRT_LOCALHOST = True

Then restart uwsgi service with

```
user@user:~/mist.io$ ./bin/supervisorctl restart uwsgi
```

**Comment by dalenoe** [comment]
@mgogoulos There is no settings.py in the root directory? Isn't one in the repository either.

**Comment by dalenoe** [comment]
I figured it out. Now just to get the host to see the virtual machines.

**Comment by mgogoulos** [comment]
Exactly, you have to create the file in the root directory if it does not exist. File settings.py can be used for user defined settings, there are other options that src/mist/io/config.py tries to read from this file and uses them - in case it can find them. 

Regards
