### ISSUE TITLE
Unable to start the machine (KVM private cloud)

### ISSUE THREAD

**Issue by junhuy** [mistio/mist.io#739]
I am able to see all of the VMs but when I tried to start a machine through the web ui (KVM hypervisor), it failed with the message "Failed to start machine" and the log is as below.

==> var/log/uwsgi-stderr---supervisor-nTHMLt.log <==
libvirt: XML-RPC error : Cannot recv data: Permission denied (publickey,password).: Connection reset by peer
2016-04-25 16:34:33,946 ERROR uWSGIWorker2Core0 methods - _machine_action: Error while connecting to cloud
2016-04-25 16:34:33,978 INFO uWSGIWorker2Core0 views - exception_handler_mist: MistError: CloudUnavailableError('Cloud unavailable',)
[pid: 15217|app: 0|req: 368/1681] 127.0.0.1 () {52 vars in 937 bytes} [Mon Apr 25 16:34:32 2016] POST /clouds/uad3FnkpUpaWbZCWdGxJdGBFFYc/machines/3f654407-0890-40ef-c8dc-57b66eae2f44 => generated 17 bytes in 1543 msecs (HTTP/1.0 503) 2 headers in 96 bytes (1 switches on core 0)

What is the permission that it failed to get and how should I correct that?

**Comment by junhuy** [comment]
I accidentally removed the key for the kvm server and hence unable to start the VM.

**Comment by mgogoulos** [comment]
Hi, there are more featured scheduled for KVM for the next few months, stay tunned!
