### ISSUE TITLE
Difference between shutdown and destroy?

### ISSUE THREAD

**Issue by junhuy** [mistio/mist.io#745]
I tried to shutdown and destroy the VM but both of them seem like doing the same thing to me. Is there any distinct difference between them?

**Comment by mgogoulos** [comment]
Hi, have a look here: http://wiki.libvirt.org/page/VM_lifecycle

Destroy is like "An inelegant shutdown, also known as hard-stop"

**Comment by mgogoulos** [comment]
While undefine deletes the domain and also removes the XML configuration

**Comment by junhuy** [comment]
The term destroy is confusing in my opinion, I assumed it stops and undefine it at the same time. Maybe Force shutdown or power-off will be more appropriate.

**Comment by mgogoulos** [comment]
it is confusing, I agree, but it is the standard KVM terminology, so we have kept it as is!
