### ISSUE TITLE
Install documentation / missing bin dir

### ISSUE THREAD

**Issue by kilmarnock** [mistio/mist.io#831]
Hi!
Please, I have no clue. I clone the repository to an ubuntu machine, and then I do what?

./bin/supervisord does not exist, obviously.

./setup.py just hangs there. 

Please help.

**Comment by Clopy** [comment]
Hi kilmarock!

There are two ways of installing mist.io. The easiest by far is using docker. You just need to:
docker pull mist/mistio
and then:
docker run -d -p 8000:8000 mist/mistio

that will start mist.io at port 8000

If you don't want to use docker, you can use buildout. Before you start supervisor, you should run:
git clone https://github.com/mistio/mist.io.git
cd mist.io
virtualenv --no-site-packages .
./bin/python bootstrap.py
./bin/buildout -v

That will create supervisord. You can find installation instructions at: https://github.com/mistio/mist.io

**Comment by kilmarnock** [comment]
Thank you very much!

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
