### ISSUE TITLE
Shell API not available?

### ISSUE THREAD

**Issue by dezull** [mistio/mist.io#863]
Hi,

I could not manage to use the **Shell API** as in the documentation here https://mist.io/docs/rest_api.html on our local deployment.

I don't do python, but don't see the endpoint defined in [src/mist/io/\__init\__.py](https://github.com/mistio/mist.io/blob/master/src/mist/io/__init__.py) (I believe that is the file?).

Is it available?

**Comment by mgogoulos** [comment]
Hi dezull, 

you are right, this is the file for the endpoints, but that call is deprecated indeed. The web shell is being implemented via websockets and not through an API POST request. 

If I understand well, you are trying to run ssh commands to a server via the API?

**Comment by dezull** [comment]
Hi,

Thanks, yes I was trying to access the hypervisor via the shell. I managed to re-implement the old shell API, just for a quick & dirty implementation for our use case.

So I think I can close this for now, thanks.
