### ISSUE TITLE
Buildout 404 error getting certifi

### ISSUE THREAD

**Issue by Jacob843** [mistio/mist.io#877]
Hello,

  I followed the steps in the readme to install mist.io, but when I run buildout, I get a 404 error trying to grab certifi. I manually installed it via pip hoping it would detect it and bypass the download, but alas no luck. I went to the url (at the end of the below log) and it indeed doesn't exist. What's the recommendation to bypass this? Thanks!

I am running Debian 8 with Python 2.7.9 with pip installed.

> Installing 'mr.developer'.
> We have the best distribution that satisfies 'mr.developer'.
> Picked: mr.developer = 1.34
> mr.developer: Queued 'deploy_collectd' for checkout.
> mr.developer: Queued 'libcloud' for checkout.
> mr.developer: Skipped checkout of existing package 'deploy_collectd'.
> mr.developer: Skipped checkout of existing package 'libcloud'.
> Installing 'zc.buildout', 'setuptools'.
> We have the best distribution that satisfies 'zc.buildout>=2.5.2'.
> Picked: zc.buildout = 2.5.2
> We have the best distribution that satisfies 'setuptools'.
> Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.8.8.tar.gz#md5=b57513f7670482da45bb350b792f659e' from setuptools 26.0.0
> Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 26.0.0
> Picked: setuptools = 26.0.0
> Develop: '/home/jhartmann/mist.io/.'
> warning: no files found matching '_.ico' under directory 'mistio'
> warning: no files found matching '_.png' under directory 'mistio'
> warning: no files found matching '_.css' under directory 'mistio'
> warning: no files found matching '_.gif' under directory 'mistio'
> warning: no files found matching '_.jpg' under directory 'mistio'
> warning: no files found matching '_.pt' under directory 'mistio'
> warning: no files found matching '_.txt' under directory 'mistio'
> warning: no files found matching '_.mak' under directory 'mistio'
> warning: no files found matching '_.mako' under directory 'mistio'
> warning: no files found matching '_.js' under directory 'mistio'
> warning: no files found matching '_.html' under directory 'mistio'
> warning: no files found matching '_.xml' under directory 'mistio'
> Develop: '/home/jhartmann/mist.io/src/libcloud'
> /home/jhartmann/mist.io/eggs/setuptools-26.0.0-py2.7.egg/setuptools/dist.py:364: UserWarning: Normalizing '1.0.0-rc2' to '1.0.0rc2'
> no previously-included directories found matching 'libcloud/test/secrets.py'
> Installing 'zc.recipe.egg'.
> We have the best distribution that satisfies 'zc.recipe.egg>=2.0.0a3'.
> Picked: zc.recipe.egg = 2.0.3
> Installing 'collective.recipe.pip'.
> We have the best distribution that satisfies 'collective.recipe.pip'.
> Adding find link 'https://github.com/minddistrict/mr.scripty/archive/4bbfa2b48b7bc8a215c80a19e61ac39d0c9545aa.zip#egg=mr.scripty' from collective.recipe.pip 0.3.4
> Picked: collective.recipe.pip = 0.3.4
> Installing 'unweb.recipe.uwsgi'.
> We have the best distribution that satisfies 'unweb.recipe.uwsgi'.
> Picked: unweb.recipe.uwsgi = 0.4
> Getting required 'PasteDeploy'
>   required by unweb.recipe.uwsgi 0.4.
> We have the best distribution that satisfies 'PasteDeploy'.
> Picked: PasteDeploy = 1.5.2
> Installing 'plone.recipe.haproxy'.
> We have the best distribution that satisfies 'plone.recipe.haproxy'.
> Picked: plone.recipe.haproxy = 1.1.2
> Installing 'gocept.download'.
> We have the best distribution that satisfies 'gocept.download'.
> Picked: gocept.download = 0.9.5
> Installing 'collective.recipe.template'.
> We have the best distribution that satisfies 'collective.recipe.template'.
> Picked: collective.recipe.template = 1.13
> Installing 'hexagonit.recipe.cmmi'.
> We have the best distribution that satisfies 'hexagonit.recipe.cmmi'.
> Picked: hexagonit.recipe.cmmi = 2.0
> Getting required 'hexagonit.recipe.download'
>   required by hexagonit.recipe.cmmi 2.0.
> We have the best distribution that satisfies 'hexagonit.recipe.download'.
> Picked: hexagonit.recipe.download = 1.7.1
> Installing 'collective.recipe.supervisor'.
> We have the best distribution that satisfies 'collective.recipe.supervisor'.
> Picked: collective.recipe.supervisor = 0.20
> Installing 'gp.recipe.node'.
> We have the best distribution that satisfies 'gp.recipe.node'.
> Picked: gp.recipe.node = 6.2.2.1
> Getting required 'python-archive'
>   required by gp.recipe.node 6.2.2.1.
> We have the best distribution that satisfies 'python-archive'.
> Picked: python-archive = 0.2
> Getting required 'zc.recipe.cmmi'
>   required by gp.recipe.node 6.2.2.1.
> We have the best distribution that satisfies 'zc.recipe.cmmi'.
> Picked: zc.recipe.cmmi = 1.3.6
> Installing 'collective.recipe.cmd'.
> We have the best distribution that satisfies 'collective.recipe.cmd'.
> Picked: collective.recipe.cmd = 0.11
> Updating _mr.developer.
> Installing 'mr.developer'.
> We have the best distribution that satisfies 'mr.developer'.
> Picked: mr.developer = 1.34
> Getting required 'zc.buildout>=2.5.2'
> We have the best distribution that satisfies 'zc.buildout>=2.5.2'.
> Picked: zc.buildout = 2.5.2
> Getting required 'setuptools'
>   required by mr.developer 1.34.
> We have the best distribution that satisfies 'setuptools'.
> Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.8.8.tar.gz#md5=b57513f7670482da45bb350b792f659e' from setuptools 26.0.0
> Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 26.0.0
> Picked: setuptools = 26.0.0
> Updating pip.
> Installing mist.
> Installing 'mist.io', 'PasteScript', 'PasteDeploy==1.5.2', 'PasteScript==2.0.2', 'PyYAML==3.11', 'Sphinx==1.3.5', 'amqp==1.4.6', 'ansible==1.9.3', 'apache-libcloud', 'behave==1.2.5', 'behaving==1.4.1', 'celery==3.1.17', 'gevent-subprocess==0.1.1', 'gevent==1.0.2', 'netaddr==0.7.18', 'paramiko==1.16.0', 'pika==0.10.0', 'pycrypto==2.6.1', 'pyramid==1.4', 'pytest==2.8.7', 'python-memcached==1.57', 'requests==2.7.0', 'selenium==2.52.0', 'sockjs-tornado==1.0.2', 'sphinx-bootstrap-theme==0.4.7', 'sphinx-rtd-theme==0.1.8', 'sphinxcontrib-httpdomain==1.4.0', 'websocket-client==0.29.0'.
> We have a develop egg: mist.io 0.9.9
> Develop distribution: mist.io 0.9.9
> uses namespace packages but the distribution does not require setuptools.
> We have the best distribution that satisfies 'setuptools'.
> Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.8.8.tar.gz#md5=b57513f7670482da45bb350b792f659e' from setuptools 26.0.0
> Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 26.0.0
> Picked: setuptools = 26.0.0
> We have the best distribution that satisfies 'PasteScript'.
> Picked: PasteScript = 2.0.2
> We have the distribution that satisfies 'PasteDeploy==1.5.2'.
> We have the distribution that satisfies 'PasteScript==2.0.2'.
> We have the distribution that satisfies 'PyYAML==3.11'.
> We have the distribution that satisfies 'Sphinx==1.3.5'.
> We have the distribution that satisfies 'amqp==1.4.6'.
> We have the distribution that satisfies 'ansible==1.9.3'.
> We have a develop egg: apache-libcloud 1.0.0rc2
> We have the distribution that satisfies 'behave==1.2.5'.
> We have the distribution that satisfies 'behaving==1.4.1'.
> We have the distribution that satisfies 'celery==3.1.17'.
> We have the distribution that satisfies 'gevent-subprocess==0.1.1'.
> We have the distribution that satisfies 'gevent==1.0.2'.
> We have the distribution that satisfies 'netaddr==0.7.18'.
> We have the distribution that satisfies 'paramiko==1.16.0'.
> We have the distribution that satisfies 'pika==0.10.0'.
> We have the distribution that satisfies 'pycrypto==2.6.1'.
> We have the distribution that satisfies 'pyramid==1.4'.
> We have the distribution that satisfies 'pytest==2.8.7'.
> We have the distribution that satisfies 'python-memcached==1.57'.
> We have the distribution that satisfies 'requests==2.7.0'.
> We have the distribution that satisfies 'selenium==2.52.0'.
> We have the distribution that satisfies 'sockjs-tornado==1.0.2'.
> We have the distribution that satisfies 'sphinx-bootstrap-theme==0.4.7'.
> We have the distribution that satisfies 'sphinx-rtd-theme==0.1.8'.
> We have the distribution that satisfies 'sphinxcontrib-httpdomain==1.4.0'.
> We have the distribution that satisfies 'websocket-client==0.29.0'.
> Getting required 'six'
>   required by websocket-client 0.29.0.
>   required by behave 1.2.5.
>   required by sphinxcontrib-httpdomain 1.4.0.
>   required by python-memcached 1.57.
>   required by PasteScript 2.0.2.
> We have the best distribution that satisfies 'six'.
> Picked: six = 1.10.0
> Getting required 'tornado>=2.1.1'
>   required by sockjs-tornado 1.0.2.
> We have the best distribution that satisfies 'tornado>=2.1.1'.
> Picked: tornado = 4.4.1
> Getting required 'py>=1.4.29'
>   required by pytest 2.8.7.
> We have the best distribution that satisfies 'py>=1.4.29'.
> Picked: py = 1.4.31
> Getting required 'translationstring>=0.4'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'translationstring>=0.4'.
> Picked: translationstring = 1.3
> Getting required 'venusian>=1.0a3'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'venusian>=1.0a3'.
> Picked: venusian = 1.0
> Getting required 'zope.deprecation>=3.5.0'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'zope.deprecation>=3.5.0'.
> Picked: zope.deprecation = 4.1.2
> Getting required 'zope.interface>=3.8.0'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'zope.interface>=3.8.0'.
> Picked: zope.interface = 4.2.0
> Getting required 'repoze.lru>=0.4'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'repoze.lru>=0.4'.
> Picked: repoze.lru = 0.6
> Getting required 'WebOb>=1.2b3'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'WebOb>=1.2b3'.
> Picked: WebOb = 1.6.1
> Getting required 'Mako>=0.3.6'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'Mako>=0.3.6'.
> Picked: Mako = 1.0.4
> Getting required 'Chameleon>=1.2.3'
>   required by pyramid 1.4.
> We have the best distribution that satisfies 'Chameleon>=1.2.3'.
> Picked: Chameleon = 2.24
> Getting required 'ecdsa>=0.11'
>   required by paramiko 1.16.0.
> We have the best distribution that satisfies 'ecdsa>=0.11'.
> Picked: ecdsa = 0.13
> Getting required 'greenlet>=0.4.7'
>   required by gevent 1.0.2.
> We have the best distribution that satisfies 'greenlet>=0.4.7'.
> Picked: greenlet = 0.4.10
> Getting required 'kombu==3.0.26'
> We have the distribution that satisfies 'kombu==3.0.26'.
> Getting required 'billiard<3.4,>=3.3.0.19'
>   required by celery 3.1.17.
> We have the best distribution that satisfies 'billiard<3.4,>=3.3.0.19'.
> Picked: billiard = 3.3.0.23
> Getting required 'pytz>dev'
>   required by celery 3.1.17.
> We have the best distribution that satisfies 'pytz>dev'.
> Picked: pytz = 2016.6.1
> Getting required 'splinter'
>   required by behaving 1.4.1.
> We have the best distribution that satisfies 'splinter'.
> Picked: splinter = 0.7.4
> Getting required 'parse'
>   required by behaving 1.4.1.
> We have the best distribution that satisfies 'parse'.
> Picked: parse = 1.6.6
> Getting required 'parse_type>=0.3.4'
>   required by behave 1.2.5.
> We have the best distribution that satisfies 'parse_type>=0.3.4'.
> Picked: parse-type = 0.3.4
> Getting required 'jinja2'
>   required by ansible 1.9.3.
> We have the best distribution that satisfies 'jinja2'.
> Picked: Jinja2 = 2.8
> Getting required 'alabaster<0.8,>=0.7'
>   required by Sphinx 1.3.5.
> We have the best distribution that satisfies 'alabaster<0.8,>=0.7'.
> Picked: alabaster = 0.7.9
> Getting required 'babel!=2.0,>=1.3'
>   required by Sphinx 1.3.5.
> We have the best distribution that satisfies 'babel!=2.0,>=1.3'.
> Picked: Babel = 2.3.4
> Getting required 'snowballstemmer>=1.1'
>   required by Sphinx 1.3.5.
> We have the best distribution that satisfies 'snowballstemmer>=1.1'.
> Picked: snowballstemmer = 1.2.1
> Getting required 'docutils>=0.11'
>   required by Sphinx 1.3.5.
> We have the best distribution that satisfies 'docutils>=0.11'.
> Picked: docutils = 0.12
> Getting required 'Pygments>=2.0'
>   required by Sphinx 1.3.5.
> We have the best distribution that satisfies 'Pygments>=2.0'.
> Picked: Pygments = 2.1.3
> Getting required 'Paste>=1.3'
>   required by PasteScript 2.0.2.
> We have the best distribution that satisfies 'Paste>=1.3'.
> Picked: Paste = 2.0.3
> Getting required 'backports_abc>=0.4'
>   required by tornado 4.4.1.
> We have the best distribution that satisfies 'backports_abc>=0.4'.
> Picked: backports-abc = 0.4
> Getting required 'certifi'
>   required by tornado 4.4.1.
> We have no distributions for certifi that satisfies 'certifi'.
> Getting distribution for 'certifi'.
> While:
>   Installing mist.
>   Getting distribution for 'certifi'.
> Error: Can't download https://pypi.python.org/packages/source/c/certifi/certifi-2016.8.8.tar.gz#md5=b57513f7670482da45bb350b792f659e: 404 Not Found

**Comment by Jacob843** [comment]
Fixed by downloading the wheel file and converting it to an .egg. This means it is still broken and should just be a temp workaround until the DL url is updated.

**Comment by FreeLinuxUser** [comment]
@Jacob843 How did you fix this issue?
I have the same error.
Thanks

**Comment by mgogoulos** [comment]
Try to pin an older version of package certifi and let us know if the buildout finishes without problem.
Eg

vi requirements.txt and add line

```
certifi==2015.9.6
```

now re-run the buildout 

```
./bin/buildout -vN
```

You can also try the docker image of mist.io. The next release of mist.io which will contains a new UI and new features, will mainly be released through the docker image. 

Cheers,
Markos

**Comment by FreeLinuxUser** [comment]
@mgogoulos 
Seems that can work,I got this

We have no distributions for certifi that satisfies 'certifi==2015.9.6'.
Getting distribution for 'certifi==2015.9.6'.

But I got this error:

While:
  Installing mist.
Error: There is a version conflict.
We already have: selenium 2.52.0
but splinter 0.7.4 requires 'selenium>=2.53.6'.


I will try again when I  have time.
Thanks

**Comment by heradon** [comment]
add 
selenium==2.53.6

to requirements.txt now it works ;)

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
