### ISSUE TITLE
Missing packages listed when running install in CentOS 6.8

### ISSUE THREAD

**Issue by mcajina74** [mistio/mist.io#878]
I get several "no package" warnings when I run the 'yum install git' command shown on the home page from CentOS 6.8:
python-virtualenv
python-dev
erlang
python-zc-buildout

The rest are either already installed or dependencies are resolved. I cancelled the installation. How can I get these packages?

**Comment by weeix** [comment]
You might need to enabled EPEL repository

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
