### ISSUE TITLE
Newly created droplets not displaying

### ISSUE THREAD

**Issue by hundredacres** [mistio/mist.io#879]
Creating new droplets in Digital Ocean and they're not being displayed in the GUI. Is there a limit to the number of machines that can be managed or displayed?

**Comment by mgogoulos** [comment]
Hi, 

if the droplet has been successfully created, it should appear in a few seconds after being created. Every 10 seconds the UI asks the list of machines for all clouds that have been added and there's no limit as to the number of machines managed or displayed.

The next release of mist.io coming soon will contain a logs section so you can see the log of the API call and know if it has succeeded or failed. Until then, if you want to know what has been the error, check the logs dir

```
tail -f var/log/*.log
```

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io

This includes detailed logs including machine actions
