### ISSUE TITLE
mistio credentials

### ISSUE THREAD

**Issue by jpstaub** [mistio/mist.io#881]
Hello,

I'm trying to implement authentication for open mistio. However, there doesn't appear to be a text editor included in the Docker image. I would like to add nano or vim but mistio doesn't have permissions to do so within the Docker container. What are mistio's credentials?

Regards,
Jake

**Comment by mgogoulos** [comment]
Hi, 
let me update the docker image to contain sudo/vim/nano and I'll let you know once this is done

**Comment by jpstaub** [comment]
Hello,

I'm still interested in mistio credentials in order to implement mistio authentication. At this point, I'm after installation of Apache2-utils to implement basic authentication in accordance with[ jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy). 

I really appreciate mistio-docker but it's a drag not having a rudimentary ability to make necessary changes.  

Regards,
Jake

**Comment by jpstaub** [comment]
Finally cracked the nut on jwilder reverse proxy basic authentication.

[mist.io](https://hub.docker.com/r/mist/mistio) does not include an authentication service. However, [jwilder nginx-proxy](https://github.com/jwilder/nginx-proxy) includes basic authentication support.

jwilder makes use of [htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html). Creating a password file requires [apache2-utils](https://www.howtoinstall.co/en/ubuntu/xenial/apache2-utils).

Sample htpasswd code:
`~$ htpasswd -b ~/htpasswd/virtualHost user password`


Note: It may be necessary to create `~/htpasswd/virtualHost` manually in order to use htpasswd to create users and passwords.

Sample Docker code (includes code for [letsencrypt](https://github.com/JrCs/docker-nginx-proxy-letsencrypt)):
```
#nginx-proxy - letsencrypt + authentication

~$ docker run -d \
--name nginx-proxy_cryptAccess \
-p 80:80 -p 443:443 \
-v /etc/nginx/certs:/etc/nginx/certs:ro \
-v /etc/nginx/vhost.d \
-v /usr/share/nginx/html \
-v /var/run/docker.sock:/tmp/docker.sock:ro \
-v ~/htpasswd/virtualHost:/etc/nginx/htpasswd/virtualHost:ro \
--restart unless-stopped \
jwilder/nginx-proxy
```

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, including user management. Check updated instructions on https://github.com/mistio/mist.io
