### ISSUE TITLE
Messy Display when many VMs

### ISSUE THREAD

**Issue by benyanke** [mistio/mist.io#889]
When there's a lot of VMs, it's difficult to view what's going on, and there's no easy way to organize. If I were to code something up, would you accept a PR?

**Comment by mgogoulos** [comment]
Hi, 

we've been rewriting the UI for the last few months, the new one is based on polymer and web components and besides the improvement on aesthetics it adds more functionality like the ability to sort per cloud/state/tag, plus it is more stable. You can see it on the Saas - https://mist.io - this will also be available on the open source mist.io in the next 2 months and will include lots of other changes (scripts, logs, monitoring, authentication etc). Have a look on the new UI on the Saas and let us know what you think! 

Once this gets to the open source mist.io we would be very glad to receive PRs. 

Cheers,
Markos

**Comment by benyanke** [comment]
Great, thank you! I will check out the saas version, and look forward to it coming to the open source version too!
