### ISSUE TITLE
Docker image is out of date?

### ISSUE THREAD

**Issue by simonvanderveldt** [mistio/mist.io#891]
Dear mist.io team, it seems the Docker image is pretty out of date, last build was 7 months ago https://registry.hub.docker.com/u/mist/mistio/.
Has something gone wrong that it isn't updated?

**Comment by mgogoulos** [comment]
Hi, 

the docker image is indeed out of date, but we plan to roll out a major release in the next 2 months, this will include most of the features that are available now on the Saas - https://mist.io- most notably a new and more intuitive UI, scripts library, user login, monitoring support and more.

**Comment by gedw99** [comment]
Sounds promising.

I have been using the SaaS version and it looks to be very different from the community it version.

Could you make your roadmap a bit more open perhaps ?
For example I am using mist to run KVM based desktops for developers environments where they need nothing on their local laptop with everything flowing via rdp or vnc.

This has radically in reader productivity because they can live code against all the microservices and the larger amounts of data.
But also we have a common used development environment. When a dev needs a desktop build for osx we are still a bit stuck. Not many osx cloud out there :)

**Comment by mgogoulos** [comment]
Hi, 

once we make this release we will be more open regarding the roadmap. But for now we're trying to get it out, and the primary channel will be docker image. This will include most of the functionality of the Saas, and the ability to login as user, except the RBAC functionality that will be part of the Saas only. 

Regards

**Comment by gedw99** [comment]
@mgogoulos Sounds good - thansk for the response.

I will see if i can help as you go through it.

**Comment by jasonmicron** [comment]
Hi, any update on the docker image?  It still seems very out of date.

**Comment by DarkBlaez** [comment]
Whys is there no update on this? The docker image is stale and so is the git repo from which is it derived. Likewise in the main code repo there are many out-of-date dependencies and references

**Comment by mgogoulos** [comment]
Hi, 

you are right, we are almost there! The new release will be out in the next 2 weeks, we have decided to move most of the functionality that is available on the Saas version -https://mist.io - and this has resulted in extra development time.

**Comment by deltcloud** [comment]
@mgogoulos,  hi,how about the new release

**Comment by mgogoulos** [comment]
Hi @deltcloud , 

we are testing the image internally and will release it in a few days, thanks for the patience

**Comment by mgogoulos** [comment]
I'm pleased to announce that the new version is out, and it is our biggest open-source release so far! It comes with an easier installation process using Docker Compose and many new features:

Support for more providers
Faster and better designed UI
Run scripts and Ansible playbooks
Schedule actions
Manage DNS records, networks and logs
User and team management 
Estimation of infrastructure costs
Last but not least, the tagging mechanism has been vastly improved and is deeply integrated with the scheduler and the cost management system

To install, check the new instructions on https://github.com/mistio/mist.io
