### ISSUE TITLE
Running mist.io in docker container controlling KVM on same host

### ISSUE THREAD

**Issue by jryburn** [mistio/mist.io#894]
I have a very similar issue as https://github.com/mistio/mist.io/issues/692. However, I am running mist.io inside a docker container. I tried opening up a bash shell in the container but I cannot find a tool that allows me to edit the config.py file and set ALLOW_LIBVIRT_LOCALHOST to True.

**Comment by mgogoulos** [comment]
Hi, 
mist.io docker image currently uploaded on https://hub.docker.com/r/mist/ lacks some tools unfortunately (as vi editor). We will release the new version late February and this will include lots of features that are now available on the Saas (as scripts, logs and the ability to login with user accounts), plus bugfixes. I'm sure that this new release will compensate you for this trouble!

**Comment by markhowells** [comment]
To add a packeage (eg vim), first find the containername
```
root@host# docker ps -a
CONTAINER ID        IMAGE               COMMAND                 CREATED             STATUS              PORTS                    NAMES
ca8e14a2212c        mist/mistio         "/bin/sh -c /init.sh"   13 minutes ago      Up 7 minutes        0.0.0.0:8000->8000/tcp   eloquent_mestorf
```
Note the conainer name - 'eloquent_mestorf` in my case. Now exec in as root,
```
root@host# docker exec -it --user=0 eloquent_mestorf bash
root@ca8e14a2212c:/home/mist/mist.io#
```

and once in - just add whatever you want in the normal way.

```
apt-get update && apt-get install vim
...
```

**Comment by mgogoulos** [comment]
@markhowells thanks for adding this! Hope this helps, until the new release gets out. 

Regards

**Comment by jryburn** [comment]
Thanks @markhowells that worked. Should we close this issue or wait for the new docker image that contains vim?

**Comment by mgogoulos** [comment]
Closing, will make changes to the Readme page plus update a few other issues that are related to the current version once the new release is out
