### ISSUE TITLE
Support for Ubuntu MaaS

### ISSUE THREAD

**Issue by 64b2b6d12b** [mistio/mist.io#895]
It would be great to see support for [Ubuntu MaaS](https://maas.io/). Maas (Metal as a Service) allows Bare Metal servers to be spun up and down like cloud VM's and provisions said servers with both Windows and Linux images. They have a very well documented [RESTful API](http://docs.maas.io/2.1/api.html?_ga=1.146940286.890110127.1485123968) which makes it perfect to be integrated with Mist.

**Comment by mgogoulos** [comment]
Hi, 
this is not on our dev roadmap but could be added in the future, specially if it has a well documented API.

Regards,
Markos

**Comment by 64b2b6d12b** [comment]
Thanks @mgogoulos
