### ISSUE TITLE
additional build dependencies

### ISSUE THREAD

**Issue by tmakatos** [mistio/mist.io#897]
On Debian 7, the following packages need to be installed:
* six
* packaging
* appdirs

libffi-dev, automake need to be installed.

pip in the virtual environment is very old, it needs upgrading as follows:
```bin/pip install pip --upgrade```

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, checl updated instructions on https://github.com/mistio/mist.io
