### ISSUE TITLE
Missing build steps for Centos7

### ISSUE THREAD

**Issue by jasonmicron** [mistio/mist.io#900]
Hello,

The instructions for installation are very intuitive, however there were some missing steps in the process that I'd like to recommend get added to the guide.  This was specific to CentOS 7 on a clean installation utilizing ONLY the official repos and the repos from your guide in a minimal install:

```
git clone https://github.com/mistio/mist.io.git
cd mist.io
virtualenv --no-site-packages .
./bin/pip install --upgrade pip
./bin/pip install setup_tools --upgrade
./bin/pip install six packaging appdirs
./bin/python bootstrap.py
./bin/buildout -v
```

**Comment by DarkBlaez** [comment]
I'd also recommend adding this to the pip install

/bin/pip install six packaging appdirs IPython==5.3.0

Seems without this there is the attempt to install the latest which is 6.0+ and that requires Python 3.3 or greater. Without this the build will fail on Centos 7.3

DB

**Comment by DarkBlaez** [comment]
The only other comment I is why haproxy is being installed from:

http://haproxy.1wt.eu/download/1.5/src/haproxy-1.5.14.tar.gz

There are plenty of verified was to install this and this does fail the CRC check on the build (IOError: CRC check failed 0x95777e99 != 0xd1f4f749L)

**Comment by DarkBlaez** [comment]
Something to note as well, haproxy 1.5 that is referenced in the plone (buildout.cfg) errors our on a CRC check

**Comment by mgogoulos** [comment]
Hi @DarkBlaez , thanks for the update, the new version will be available through docker image mostly, there will be the option to install through buildout but it won't be supported as the docker image.

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
