### ISSUE TITLE
Instance monthly cost

### ISSUE THREAD

**Issue by mcrypt** [mistio/mist.io#909]
Linode 1024 instance cost calculated through the API seems to be priced wrong. Its actually $5/mo or (.0075/hr). Monthly cost is reported at $10.00 in mistio. I did correct the value by setting a reserved tag!

**Comment by mgogoulos** [comment]
Thanks for reporting, we are going to update the price for most of the cloud providers (ec2/gce/rackspace/linode/digitalocean) in the next release coming out
