### ISSUE TITLE
[GCE] Crontab schedules wont work

### ISSUE THREAD

**Issue by boristunity** [mistio/mist.io#910]
I configured 2 schedules based on crontab, one is to shutdown entire environment, and the other is to start entire environment.

They both wont work, And I cant find any related logs,
This is the schedule job:

![screen shot 2017-07-03 at 12 53 33](https://user-images.githubusercontent.com/20415463/27787855-fca64d50-5fee-11e7-9849-98c39f56c72f.png)

**Comment by boristunity** [comment]
I have instance groups, which I usually change the amount of instances to 0, and every time I change it bake to a different number than 0 it will bring them up with different name.

So I guess this system cant handle instance groups yet

**Comment by boristunity** [comment]
The crontab is working properly, 
I still cant understand why it wont work.

I will try today `Run now`,
But how can I make it run every day- as the crontab states ?

**Comment by mgogoulos** [comment]
Hi, 

your crontab seems OK, you can make it a little shorter as 

```
0 7 * * 1-5
```
This should run Mo-Fri, 7am .  

The scheduler is generic for all clouds the platform supports, there's no instance group concept for the scheduler. You have to either select manually all machines that interest you, which works well on a list of machines that doesn't change all the time, or if this is a dynamic list (as I imagine with instance groups that you have) it makes sense to select through a tag.
 From the machines listing page, you can select as many of the machines that interest you and set a tag (eg dev). On the scheduler page specify this tag

![t](https://user-images.githubusercontent.com/1027116/27799541-4209e800-601e-11e7-91d6-a92b94835caa.png)

This works dynamically, any time the scheduler is going to run, it will run towards any machine that it finds that it has this tag. Tags can be either values, or key:value, so dev and role:dev are both possible. 

You can start by setting a tag on machines now, and any time you have new machines appearing on the list that you want them to be handled through the scheduler, add the tag to them as well. 

Hope this helps,
Markos

**Comment by mgogoulos** [comment]
Did you have any chance to try this? 

Cheers

**Comment by boristunity** [comment]
Hi ,
Sorry for the delay- I decided to not use mistio eventually.
