### ISSUE TITLE
Bare Metal Monitoring not working

### ISSUE THREAD

**Issue by abel408** [mistio/mist.io#912]
I have just set up my on-premise install of mist.io using docker-compose. I have added my ssh key and a couple servers. For some reason, I am not seeing the monitoring section of these machines. When I click the machines, I just have basic info (Which is missing a lot of info) and Machine Logs.

Also, when I try to probe the server, I get this error:
Error probing machine Required parameter not provided: host

I am able to remotely reboot the server and connect to shell though.

**Comment by dimrozakis** [comment]
Hey @abel408 

>For some reason, I am not seeing the monitoring section of these machines.

Monitoring hasn't **yet** been migrated to the open source mist.io version, it's currently only available on the SaaS version.

>Also, when I try to probe the server, I get this error:
>Error probing machine Required parameter not provided: host

We're aware of this issue, it'll be fixed in the next release.
