### ISSUE TITLE
KVM/libvirt local connection through UNIX socket

### ISSUE THREAD

**Issue by hesdago** [mistio/mist.io#916]
I'm trying to integrate mist.io into my local setup, and plan on using it to manage local KVM/libvirt VMs.

I understand from the documentation that UNIX socket connection is supported, by enabling 

`ALLOW_LIBVIRT_LOCALHOST = True` in `config/settings.py` and using `localhost ` as Hostname.

However this step is not sufficient as with the current docker-compose deployment, the local socket is not available: `Cloud unavailable: Connection error`

I'm assuming the libvirt socket `/var/run/libvirt/libvirt-sock` should be exposed to the container as a docker volume, but unsure which container to use for this.

**Comment by mgogoulos** [comment]
Hi, 

libvirt sockets are not supported, you have to enter an ip address or a resolvable host. This is not a problem on KVM hosts but is a problem when you want to add localhost, as I assume you did. 

I did something similar, installed mist.io on a server and also installed KVM there. I now load mist.io and want to add this KVM server, localhost. 
If I specify localhost, or 127.0.0.1 it doesn't work. But it works if I specify the ip address of docker0 interface. Check with ifconfig, it should be 172.17.0.1 . So this ip address can be added as the ip of the KVM server

```
docker0   Link encap:Ethernet  HWaddr 02:42:92:74:e6:94  
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
```

**Comment by mgogoulos** [comment]
Also works if I specify the virbr0 interface (192.168.122.1 in my case, vanilla KVM on Ubuntu)

**Comment by 84ace** [comment]
127.0.0.1 doesn't work because the docker container will be connecting to its self, rather than the KVM host. Using any IP that belongs to the host should work.
