### ISSUE TITLE
"Add your images" button not working

### ISSUE THREAD

**Issue by feisuzhu** [mistio/mist.io#918]
![image](https://user-images.githubusercontent.com/857880/30125166-1e2d6ee6-936a-11e7-8098-424bdc6bfafb.png)

Fresh install with one libvirt host machine added

**Comment by mgogoulos** [comment]
Hi, 

this has been a placeholder, for previous versions, and is not available anymore. You must be using a slightly older version of mist.io. 

The way KVM works is that when you add your KVM credentials it searches for 'image files' (could be .iso, .img .qcow files) and shows you as your images. You can then create VMs through these. It does not give you the option to add new images by actually downloading them, but this is something we are thinking of adding. 

You can have a look on an article we've written regarding KVM management with mist.io, it can be found here: http://docs.mist.io/article/99-managing-kvm-with-mist-io
