### ISSUE TITLE
support Openstack Pike

### ISSUE THREAD

**Issue by s4rd1nh4** [mistio/mist.io#924]
How to troubleshoot this error?

http://prntscr.com/gy55ur

http://prntscr.com/gy56kt

**Comment by mgogoulos** [comment]
Hi, 

checkout http://docs.mist.io/article/27-adding-openstack, if you've changed the region and compute endpoint you might have to provide them as well.

Also once you have added at least a cloud, you will see a logs section on the main dashboard, that could provide more insights. 

What version of OpenStack are you using? 

Regards,
Markos

**Comment by s4rd1nh4** [comment]
Hi, thanks for reply.
I have been checked the docs.
My openstack version is Pike. 
My region is default RegionOne e compute not changed. I already tested by providing this information and the error is the same.

**Comment by mgogoulos** [comment]
Hi, 

It is on our plans to update the OpenStack integration so that Pike is supported, unfortunately this is not working now mostly due to the way authentication is performed.

Thanks and regards,
Markos

**Comment by s4rd1nh4** [comment]
Ok
