### ISSUE TITLE
Web UI not working in dev mode

### ISSUE THREAD

**Issue by ygbourhis** [mistio/mist.io#959]
Hello,

I tried to follow this documentation:

https://github.com/mistio/mist-ce/#development-deployment

in `settings/settings.py` I added my dev server's IP:

    CORE_URI = "http://172.17.0.10"

However when connecting to the web UI it seems to load forever.
The JavaScript console shows these errors:

Le script à l’adresse « http://172.17.0.10/landing/bower_components/webcomponentsjs/webcomponents-lite.js » a été chargé alors que son type MIME (« text/html ») n’est pas un type MIME JavaScript valide.
172.17.0.10
Échec du chargement pour l’élément <script> dont la source est « http://172.17.0.10/landing/bower_components/webcomponentsjs/webcomponents-lite.js ». 172.17.0.10:24:1
L’objet « Components » est obsolète. Il sera bientôt supprimé. 172.17.0.10

To make it short, it means it can't find http://172.17.0.10/landing/bower_components/webcomponentsjs/webcomponents-lite.js

I have no issues with the "non dev" mode, But I need the dev mode in order to do this:
https://blog.mist.io/post/117233356986/adding-a-new-provider-in-mistio-the-host-virtual

It seems that there are a lot of steps missing in the https://github.com/mistio/mist-ce/#development-deployment documentation for development mode.

Thanks
​

**Comment by d-mo** [comment]
Hi @ygbourhis.

You are right, the dev mode instructions are incomplete and will be updated. In the meantime, try running the following commands:
```
docker-compose exec landing bower install
docker-compose exec landing polymer build
docker-compose exec ui bower install
docker-compose exec ui node --max_old_space_size=4096 /usr/local/bin/polymer build
docker-compose exec ui cp bower_components/echarts/dist/echarts.common.min.js build/bundled/bower_components/echarts/dist/```

Keep in mind that if you want to update the UI or the landing page, it's better to set `JS_BUILD = False` in `settings/settings.py`. Otherwise, every change will require the `polymer build` steps above before you can see it live.

**Comment by ygbourhis** [comment]
Hi @d-mo thanks a lot, it worked.
